name: sqlite3
description: Provides lightweight yet convenient bindings to SQLite by using dart:ffi
version: 0.1.9-nullsafety.2
homepage: https://github.com/simolus3/sqlite3.dart/tree/master/sqlite3
issue_tracker: https://github.com/simolus3/sqlite3.dart/issues

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  collection: ^1.15.0-nullsafety.5
  ffi: ^0.2.0-nullsafety
  meta: ^1.3.0-nullsafety

dev_dependencies:
  build_ffi_generator:
    git:
      url: https://github.com/simolus3/build_ffi_generator.git
  build_runner: ^1.10.0
  extra_pedantic: ^1.2.0
  path: ^1.8.0-nullsafety
  test: ^1.16.0-nullsafety
