name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  analyze:
    strategy:
      matrix:
        package: [sqlite3]
    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: DanTup/gh-actions/setup-dart@master
      with:
        channel: dev

    - name: Pub get
      run: dart pub get
      working-directory: ${{ matrix.package }}

    - name: Format
      run: dart format --set-exit-if-changed .
      working-directory: ${{ matrix.package }}
    
    - name: Analyze
      run: dart analyze
      working-directory: ${{ matrix.package }}
    
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        dart: [dev]
    
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - uses: DanTup/gh-actions/setup-dart@master
      with:
        channel: ${{ matrix.dart }}
    
    - name: install sqlite (Linux)
      if: runner.os == 'Linux'
      run: sudo apt-get install -y libsqlite3-dev
      
    - name: install sqlite (Windows)
      if: runner.os == 'Windows'
      run: choco install sqlite
    
    - name: Test
      run: |
        pub get
        dart test
      working-directory: sqlite3/

  # Shamelessly stolen from https://medium.com/flutter-community/run-flutter-driver-tests-on-github-actions-13c639c7e4ab
  integration_test:
    runs-on: macos-latest
    steps:
      - name: List simulators
        run: "xcrun instruments -s"

      - name: Start simulator
        run: |
          UDID=$(
            xcrun instruments -s |
            awk \
              -F ' *[][]' \
              -v 'device=iPhone 12 (14.2)' \
              '$1 == device { print $2 }'
          )
          xcrun simctl boot "${UDID:?No Simulator with this name found}"
      
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      
      - name: Flutter version
        run: flutter --version
      
      - name: sqlite3 driver tests
        run: "flutter pub get && flutter pub run test_driver/integration_test.dart"
        working-directory: integration_tests/flutter_libs

      - name: sqlcipher driver tests
        run: "flutter pub get && flutter pub run test_driver/integration_test.dart"
        working-directory: integration_tests/sqlcipher_flutter